# Taps
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'

# Unix
brew 'zsh'
brew 'bash'
brew 'fish'
brew 'coreutils'
brew 'gmp'
brew 'gnu-sed'
brew 'grep'
brew 'tmux'
brew 'vim'

# Binaries
brew 'bat'
brew 'ctags'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'gh'
brew 'hub'
brew 'jq'
brew 'mas'
brew 'ripgrep'
brew 'the_silver_searcher'
brew 'thefuck'
brew 'tldr'
brew 'wget'
brew 'z'

# Pen Test
brew 'hydra'
brew 'john'
brew 'nmap'
brew 'socat'
brew 'sqlmap'

# Developer
brew 'nvm'
brew 'yarn'
brew 'python'
brew 'ruby'
brew 'perl'
brew 'php'
brew 'go'
brew 'mysql'
brew 'postgresql'
brew 'redis'
cask 'adoptopenjdk8'
brew 'elasticsearch'
brew 'diff-so-fancy'
brew 'neovim'

# Cli Tools
brew 'awscli'
brew 'broot'
brew 'cmatrix'
brew 'dasht'
brew 'gotop'
brew 'imagemagick'
brew 'navi'
brew 'neofetch'
brew 'nnn'
brew 'speedtest-cli'
brew 'streamlink'
brew 'task'
brew 'tree'
brew 'youtube-dl'

# Applications
cask 'alacritty'
cask 'alfred'
cask 'bartender'
cask 'cheatsheet'
cask 'dash'
cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'focus'
cask 'gimp'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'gpg-suite-no-mail'
cask 'iina'
cask 'imageoptim'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'java'
cask 'karabiner-elements'
cask 'keepassxc'
cask 'little-snitch'
cask 'obs'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'visual-studio-code'
cask 'vlc'

# Fonts
cask 'font-fira-code'
cask 'font-hack-nerd-font'

# Mac App Store
mas 'Xcode', id: 497799835
